name: CI with SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest

      - name: Download SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
          unzip sonar-scanner-cli-5.0.1.3006.zip
          mv sonar-scanner-5.0.1.3006 sonar-scanner
          echo "${{ github.workspace }}/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=hello-world \
            -Dsonar.sources=. \
            -Dsonar.tests=. \
            -Dsonar.python.version=3.8 \
            -Dsonar.test.inclusions=**/test_*.py \
            -Dsonar.login=$SONAR_TOKEN
